services:
  - type: web
    name: nequi-php
    env: php
    buildCommand: |
      php -v
    startCommand: php -S 0.0.0.0:$PORT -t .
    staticPublishPath: .
    preDeployCommand: |
      cp htaccess.txt .htaccess
